import Head from 'next/head';
import { GetStaticProps } from 'next';
import Link from 'next/link';
import { fetchTags } from '../utils/notion';
import TagElement from '../components/atoms/TagElement';

type Props = { nowDate: string; pageTitle: string; tags: any[]};

export const getStaticProps: GetStaticProps<Props> = async (context) => {
  const results = await fetchTags()
  return {
    props: {
      nowDate: new Date().toLocaleString(),
      pageTitle: 'ISR Demo',
      tags: results,
    },
    revalidate: 5, // ISR settings
  };
};

export default function ISRDemo(props: Props) {
  return (
    <div>
      <Head>
        <title>{props.pageTitle}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <h2>{props.pageTitle}</h2>
        <p>What time is it now?</p>
        <p>It&apos;s {props.nowDate}.</p>
        <p>
          <Link href={'/'}>
            <a>Go back</a>
          </Link>
        </p>
        {props.tags.map((tag, index) => {
          return (
            <Link key={index} href={`/tags/${tag}`}>
              <a><TagElement key={index} tag={tag}/></a>
            </Link>
          )
        })}
      </main>
    </div>
  );
}
